name: Keyvault

on:
  push:
    branches:
      - '*'
      - '!master'
      - '!main'
      - '!development'

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pre-commit, pytest
        pip install -r requirements.txt
    - name: Run pre-commit
      run: |
        pre-commit install
        pre-commit run --all-files
    - name: Test with pytest
      env:
        TEST_KEYVAULT_NAME: ${{ secrets.TEST_KEYVAULT_NAME }}
        AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
        AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      run: |
        pytest keyvault
